### ISSUE TITLE
Update known issues documentation

### ISSUE THREAD

**Issue by jhg03a** [alexharv074/puppet-disable_transparent_hugepage#3]
In your known issues list, you mention an outstanding PUP workaround.  That PUP has since been closed and is now fixed in puppet-agent-1.5.0 which is available in the official puppet repos.

**Comment by jhg03a** [comment]
And I've validated it works for me now.

**Comment by alex-harvey-z3q** [comment]
Thanks for the feedback @jhg03a - I have deprecated this feature now, and if no one contacts me, I'll remove it completely in the next release.
